# Generated by Django 5.0 on 2024-01-06 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
