# Generated by Django 5.0 on 2024-01-06 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=500)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.author')),
            ],
        ),
    ]
